services:
  api:
    container_name: 1CServices.api
    environment:
      - API_PORT=${API_PORT}
      - DB_DSN=${DB_DSN}
    image: donskova1ex/api:latest
    profiles:
      - api
    ports:
      - 8080:${API_PORT}