version: "3.9"
services:
  1c_api:
    container_name: 1CServices.1c_api
    environment:
      - API_PORT=${API_PORT}
      - SQL_DSN=${SQL_DSN}
    image: donskova1ex/1c_api:latest
    ports:
      - 1616:${API_PORT}