// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger user management service - OpenAPI 3.0
 *
 * This is a sample some endpoints for 1C
 *
 * API version: 1.0.0
 */

package openapi

type Rkobydivision struct {
	DivisionId string `json:"DivisionId,omitempty"`

	Result float32 `json:"Result,omitempty"`

	Quantity int32 `json:"Quantity,omitempty"`
}

// AssertRkobydivisionRequired checks if the required fields are not zero-ed
func AssertRkobydivisionRequired(obj Rkobydivision) error {
	return nil
}

// AssertRkobydivisionConstraints checks if the values respects the defined constraints
func AssertRkobydivisionConstraints(obj Rkobydivision) error {
	return nil
}
