openapi: 3.0.0
info:
  title: Swagger 1c services - OpenAPI 3.0
  description: |-
    This is a sample some endpoints for 1C
  version: 1.0.0
servers:
  - url: http://192.168.3.11:8080/1c_api/v1
tags:
  - name: PDNcalculation
    description: PDN calculation parametres
paths:
  /pdncalculation/{loanid}:
    get: 
      tags: 
        - PDNcalculation
      summary: Find parametres by loan id
      description: returns the loan parameters for the calculation
      operationId: getParametresByLoanId
      parameters: 
        - name: loanid
          in: path
          description: ID of loan to return
          required: true
          schema: 
            type: string
      responses: 
        '200':
          description: successful operation
          content: 
            application/json: 
              schema:
                $ref: '#/components/schemas/pdnparameters'
        '400':
          description: Invalid ID supplied
        '404':
          description: parametres not found
  /rkobydivision:
    get:
      tags:
        - RkoByDivision
      summary: Division issue for the period
      description: returns division issue for the period
      operationId: RkoByDivision
      parameters:
        - name: from
          in: query
          required: true
          schema:
            type: string
        - name: to
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/rkobydivision"
        '400':
          description: Invalid dates
        '404':
          description: parameters not found
components:
  schemas:
    pdnparameters:
      type: object
      properties: 
        LoanId:
          type: string
          example: f7dabcd1-df8b-4fe6-9666-bf123782593e
        Incomes:
          type: number
          example: 56756.07
        Expenses:
          type: number
          example: 16254.17
        IncomesTypeId:
          type: string
          example: 1
        AverageRegionIncomes:
          type: number
          example: 36587.00
    rkobydivision:
      type: object
      properties:
        DivisionId:
          type: string
          example: 123
        Result:
          type: number
          example: 56756.07
        Quantity:
          type: number
          example: 16